// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFF42AaFmT5xbB2w2Mwp3zuT9SvaQ6UKo',
    appId: '1:305657236990:web:448c492db751aa5b4144af',
    messagingSenderId: '305657236990',
    projectId: 'sendra-pro',
    authDomain: 'sendra-pro.firebaseapp.com',
    storageBucket: 'sendra-pro.firebasestorage.app',
    measurementId: 'G-4F6VVKL8BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABy9zrMY0DkyVoiIuh8MUgOlcnPIZn6ik',
    appId: '1:305657236990:android:d3a1484a5d2d84b24144af',
    messagingSenderId: '305657236990',
    projectId: 'sendra-pro',
    storageBucket: 'sendra-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2c-GEwqN8bERQVwTaEFYZWlNXYbAijoE',
    appId: '1:305657236990:ios:e6d3ce11abfd93f44144af',
    messagingSenderId: '305657236990',
    projectId: 'sendra-pro',
    storageBucket: 'sendra-pro.firebasestorage.app',
    iosBundleId: 'com.example.sendra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2c-GEwqN8bERQVwTaEFYZWlNXYbAijoE',
    appId: '1:305657236990:ios:e6d3ce11abfd93f44144af',
    messagingSenderId: '305657236990',
    projectId: 'sendra-pro',
    storageBucket: 'sendra-pro.firebasestorage.app',
    iosBundleId: 'com.example.sendra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFF42AaFmT5xbB2w2Mwp3zuT9SvaQ6UKo',
    appId: '1:305657236990:web:1a9cc271c38e6e5a4144af',
    messagingSenderId: '305657236990',
    projectId: 'sendra-pro',
    authDomain: 'sendra-pro.firebaseapp.com',
    storageBucket: 'sendra-pro.firebasestorage.app',
    measurementId: 'G-8LJGCJ0XXZ',
  );

}